# Generated by Django 5.0.1 on 2024-01-26 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.carsubmodel')),
            ],
        ),
    ]
