# Generated by Django 5.0.1 on 2024-01-26 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_carbrand_brand_rename_carmodel_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmodels', to='main.brand'),
        ),
    ]
